<?php
$quoteItems = $this->getQuoteItems();
?>

<div class="cart">
    <h1>Shopping Cart</h1>
    <?php if (count($quoteItems) > 0) : ?>
        <div class="cart-items">
            <?php foreach ($quoteItems as $quoteItem) : ?>
                <form method="post">
                    <input type="hidden" name="item_id" value="<?php echo $quoteItem->getItemId() ?>">
                    <input type="hidden" name="sales_quote[product_id]" value="<?php echo $quoteItem->getProductId() ?>">
                    <input type="hidden" name="sales_quote[item_id]" value="<?php echo $quoteItem->getItemId() ?>">

                    <div class="cart-item">
                        <img src=<?php echo $this->getUrl('media/product/' . $quoteItem->getProduct()->getImageLink()) ?> alt="Product Img">
                        <div class="item-details">
                            <p>
                                <?php echo $quoteItem->getProduct()->getName() ?>
                            </p>
                            <div>
                                <div>
                                    <label for="price">Price:</label>
                                    <input type="text" value="<?php echo "&#8377;" . $quoteItem->getPrice() ?>" id="price" disabled>
                                </div>
                                <div>
                                    <label for="qty">Quantity:</label>
                                    <input type="number" min='1' name="sales_quote[qty]" value="<?php echo $quoteItem->getQty() ?>" id="qty">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="item-actions">
                        <button formaction="<?php echo $this->getUrl('sales/quote/delete') ?>" class="delete-btn" type="submit">Delete Item</button>
                        <button formaction="<?php echo $this->getUrl('sales/quote/add') ?>" class="update-btn" type="submit">Update
                            Item</button>
                    </div>
                </form>
            <?php endforeach; ?>
        </div>
        <hr>
        <div class="cart-summary">
            <p>
                <strong>
                    <?php echo "Total Price: &#8377;" . $this->getQuote()->getGrandTotal() ?>
                </strong>
            </p>
            <a class="checkout-btn" href="<?php echo $this->getUrl('cart/checkout/index') ?>">Checkout</a>
        </div>
    <?php else : ?>
        <p class='empty-cart'>Cart is Empty!</p>
    <?php endif; ?>
</div>