<?php $order = $this->getOrders();
?>

<div class="list">
    <h2>Orders List</h2>
    <table>
        <thead>
            <tr>
                <th>Order Number</th>
                <th>Total Items</th>
                <th>Total Amount</th>
                <th>Customer Name</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($order as $_order): ?>
                <tr>
                    <td>
                        <?php echo $_order->getOrderNumber(); ?>
                    </td>
                    <td>
                        <?php echo count($_order->getItemCollection());?>
                    </td>
                    <td>
                        <?php echo $_order->getGrandTotal();?>
                    </td>
                    <td>
                        <?php echo $this->getCustomerName($_order->getCustomerId());?>
                    </td>
                    <td>
                        <?php echo $_order->getStatus();?>
                    </td>
                    <td>
                        <a
                            href="<?php echo $this->getUrl("admin/order/view?order_id={$_order->getId()}") ?>">View
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
