<?php
$productCollection = Mage::getModel("catalog/product")->getCollection();
// $productCollection->addFieldToFilter('name', 'abc');
// $productCollection->addFieldToFilter('product_id', ['in'=>[52,53,54]]);
// $productCollection->addFieldToFilter('sku', ['like'=>'%abc']);
// $productCollection->getData();
// foreach ($productCollection->getData() as $product) {
// print_r($product);
// echo $product->getCategoryId();
// echo $product->getStatus();
// echo '' . $product->getProductId();
// echo ''. $product->delete();
// }
?>

<h2>Product List</h2>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>SKU</th>
            <th>Status</th>
            <th>Color</th>
            <th colspan="2">Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($productCollection->getData() as $_product) : ?>
            <tr>
                <td>
                    <?php echo $_product->getName() ?>
                </td>
                <td>
                    <?php echo $_product->getSku() ?>
                </td>
                <td>
                    <?php echo $_product->getStatus() ?>
                </td>
                <td>
                    <?php echo $_product->getColor() ?>
                </td>
                <td class="link-container">
                    <a class="edit-link" href="<?php echo $this->getUrl("admin/catalog_product/form?id={$_product->getId()}") ?>">Update</a>
                </td>
                <td class="link-container">
                    <a class="del-link" href="<?php echo $this->getUrl("admin/catalog_product/delete?id={$_product->getId()}") ?>">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>