<div class="container">
    <form class="form" action="<?php echo $this->getUrl('sales/quote/placeOrder') ?>" method="post">
        <div>
            <h2>Payment Method</h2>
            <input type="hidden" name="quote_payment_method[quote_id]" value="<?php echo $this->getQuoteId() ?>">
            <div class="row">
                <label for="payment_method">Payment Method:</label>
                <select name="quote_payment_method[payment_method]" id="payment_method">
                    <?php foreach ($this->getPaymentMethods() as $key => $val): ?>
                        <option value='<?php echo $key ?>' class="payment_method">
                            <?php echo $val ?>
                        </option>;
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div>
            <h2>Shipping Method</h2>
            <input type="hidden" name="quote_shipping_method[quote_id]" value="<?php echo $this->getQuoteId() ?>">
            <div class="row">
                <label for="shipping_method">Shipping Method:</label>
                <select name="quote_shipping_method[shipping_method]" id="shipping_method">
                    <?php foreach ($this->getShippingMethods() as $key => $val): ?>
                        <option value='<?php echo $key ?>' class="shipping_method">
                            <?php echo $val ?>
                        </option>;
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div>
            <input type="submit" name="submit" value="Place Order">
        </div>
    </form>
</div>