<div class="card-container">
    <div class="card">
        <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
            <i class="checkmark">✓</i>
        </div>
        <h1 class="green">Success</h1>
        <h2>Your Order Number:
            <span class="green">
                <?php echo $this->getLastOrder()->getOrderNumber(); ?>
            </span>
        </h2>
        <p>We received your purchase request</p>
        <a href="<?php echo $this->getUrl('customer/order/list') ?>">Go To Order</a>
    </div>
</div>