<?php 
    $customerDetails = $this->getCustomerDetails();

?>
<div class="container">
    <header>
        <h2>Customer Dashboard</h2>
    </header>
    
    <div class="row">
        <div class="column personal-info">
            <h4>Personal Information</h4>
            <ul class="info-list">
                <li><strong>Customer ID:</strong> <span id="customer-id">1</span></li>
                <li><strong>Email:</strong> <span id="customer-email">demo@gmail.com</span></li>
                <li><strong>First Name:</strong> <span id="first-name">yash</span></li>
                <li><strong>Last Name:</strong> <span id="last-name">dhuliya</span></li>
                <li><strong>Password:</strong> <span id="password">123</span></li>
            </ul>
        </div>

        <div class="column billing-info">
            <h4>Billing Information</h4>
            <ul class="info-list">
                <li><strong>Address:</strong> <span id="billing-address"></span></li>
                <li><strong>City:</strong> <span id="billing-city"></span></li>
                <li><strong>Region:</strong> <span id="billing-region">0</span></li>
                <li><strong>Country:</strong> <span id="billing-country">0</span></li>
                <li><strong>Phone:</strong> <span id="billing-phone"></span></li>
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="column shipping-info">
            <h4>Shipping Information</h4>
            <ul class="info-list">
                <li><strong>Address:</strong> <span id="shipping-address"></span></li>
                <li><strong>City:</strong> <span id="shipping-city"></span></li>
                <li><strong>Region:</strong> <span id="shipping-region">0</span></li>
                <li><strong>Country:</strong> <span id="shipping-country">0</span></li>
                <li><strong>Phone:</strong> <span id="shipping-phone"></span></li>
            </ul>
        </div>

        <div class="column other-info">
            <h4>Other Information</h4>
            <ul class="info-list">
                <li><strong>Default:</strong> <span id="default">1</span></li>
            </ul>
        </div>
    </div>
</div>