<div class="container">
    <div class="form">
        <h2>Customer Register</h2>
        <form method="POST" action="<?php echo $this->getUrl('customer/account/save') ?>">
            <div>
                <input type="hidden" value="" name="customer[customer_id]">
            </div>
            <div class="row">
                <div>
                    <label for="customer_email">Email:</label>
                    <input type="text" value="" name="customer[customer_email]" id="customer_email">
                </div>
                <div>
                    <label for="first_name">First Name:</label>
                    <input type="text" value="" name="customer[first_name]" id="first_name">
                </div>
                <div>
                    <label for="last_name">Last Name:</label>
                    <input type="text" value="" name="customer[last_name]" id="last_name">
                </div>
                <div>
                    <label for="password">Password:</label>
                    <input type="password" value="" name="customer[password]" id="password">
                </div>
            </div>
            <div>
                <input type="submit" name="submit" value="Submit">
            </div>
        </form>
        <p>Already have an acoount? <a href="<?php echo $this->getUrl('customer/account/login') ?>">click here</a></p>
    </div>
</div>