<div class="header">
    <div class="header-left">Project</div>
    <div class="header-right">
    <div class="pill-nav" id="myDIV">
      <ul>
      <div class="dropdown"> <a class="btn"href="<?php echo$this->getUrl("");?>">Home</a></div>
      <div class="dropdown"> <a class="btn"href="<?php echo$this->getUrl("catalog/product/view");?>">Product</a></div>
      <div class="dropdown"> <a class="btn"href="<?php echo$this->getUrl("cart");?>">Cart</a></div>
      <div class="dropdown"> <a class="btn"href="<?php echo$this->getUrl("customer/order");?>">Order</a></div>

        <div class="dropdown">
        <?php if(Mage::getSingleton('core/session')->get('logged_in_customer_id')){ ?>
          <a class="btn">  Profile </a>
          <div class="dropdown-content">
            <a  href="<?php echo $this->getUrl("customer/account/dashboard"); ?>">Profile</a>
            <a  href="<?php echo $this->getUrl("customer/account/forgotpassword"); ?>">password?</a>
            <a  href="<?php echo$this->getUrl("customer/account/logout");?>">Log Out</a>

          <?php }else{ ?>
        <a class='btn'  href="<?php echo$this->getUrl("customer/account/login");?>">Login</a>
        <?php }?>
        </div>
        </div>
      </ul>
    </div>
  </div>
</div>
