<footer class="footer">
    <div class="footer-content">
        <div class="footer-section about">
            <h3>About Us</h3>
            <p>Welcome to Marketplace Platform the <br> ultimate destination for buyers and sellers <br> to connect, discover unique products, and create fulfilling shopping experiences.</p>
        </div>
        <div class="footer-section contact">
            <h3>Contact Us</h3>
            <p>Email: info@example.com<br>Phone: 123-456-7890</p>
        </div>
        <div class="footer-section links">
            <h3>Quick Links</h3>
            <ul>
                <li><a href="#">Link1</a></li>
                <li><a href="#">Link2</a></li>
                <li><a href="#">Link3</a></li>
                <li><a href="#">Link4</a></li>
            </ul>
        </div>
    </div>
    <div class="footer-bottom">
        &copy; 2024 Your Company. All rights reserved.
    </div>
</footer>