
<header class="header">
    <div class="logoContainer">
        <div class="logo">
            <img src="<?php echo Mage::getBaseUrl('skin/image/logo.jpg')?>" alt="Logo" width="55" height="40"> 
        </div>
        <span class="title">Project</span>
    </div>
    <nav class="nav">
        <ul>
            <li><a href="#">Link 1</a></li>
            <li><a href="#">Link 2</a></li>
            <li><a href="#">Link 3</a></li>
            <li><a href="#">Link 4</a></li>
        </ul>
    </nav>
</header>