<?php $js = $this->getJs(); ?>
<?php if (count($js) > 0):?>
    <?php foreach($js as $_js):?>
        <script type="" src="<?php echo Mage::getBaseUrl('skin/js/' . $_js);?>"></script>
    <?php endforeach;?>
<?php endif;?>

<?php $css = $this->getCss(); ?>
<?php if (count($css) > 0):?>
    <?php foreach($css as $_css):?>
        <link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl('skin/css/' . $_css)?>">
    <?php endforeach;?>
<?php endif;?>

