<style>
    body,
    h2,
    p,
    form {
        margin: 0;
        padding: 0;
    }
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
    }
    .form {
        margin: 50px auto;
        background-color: #fff;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    h2 {
        text-align: center;
        color: #333;
    }
    .row {
        margin-bottom: 15px;
    }
    label {
        display: block;
        margin-bottom: 5px;
        font-weight: bold;
    }
    input[type="text"],
    input[type="number"],
    textarea,
    input[type="file"] {
        width: 100%;
        padding: 8px;
        margin-top: 5px;
        box-sizing: border-box;
    }
    input[type="submit"] {
        background-color: #44bd32;
        color: #fff;
        padding: 10px 15px;
        cursor: pointer;
        border: none;
        display: block;
        margin: 0 auto;
        font-weight: bold;
        font-size: medium;
        border-radius: 5px;
    }
    input[type="submit"]:hover {
        background-color: #009432;
    }
</style>

<div class="form" style="border:1px solid black; width:35%; padding: 15px">
    <h2>Category Form</h2><br>
    <form action="">
        <div class="row">
            <label for="name">Name : </label>
            <input type="text" name="catalog_category[name]" id="name">
        </div>
        <div class="row">
            <label for="status">Status : </label>
            <input type="text" name="catalog_category[status]" id="status">
        </div>

        <div class="row">
            <input type="submit" value="Submit">
        </div>
    </form>
</div>