<div class="list">
    <h2>Product List</h2>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>SKU</th>
                <th>Color</th>
                <th colspan="2">Action</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Abc</td>
                <td>Xyz</td>
                <td>Hello</td>
                <td><a href="#">Delete</a></td>
                <td><a href="#">Update</a></td>
            </tr>
        </tbody>
    </table>
</div>