<div class="prodcard">
    <?php foreach ($this->getItem() as $product) { ?>
        <div class="card">
            <div style="align-items: center; display:flex; justify-content:center ">
                <img src="<?php echo $this->getImagePath() . $product->getImageLink();; ?>" alt="Product Image"  
                style="width: 200px; height:250px">
            </div>

            <table>
                <!-- <tr>
                    <th>ID</th>
                    <td>
                        <?php //echo $product->getProductId(); 
                        ?>
                    </td>
                </tr> -->
                <tr>
                    <th>Name</th>
                    <td>
                        <?php echo $product->getName(); ?>
                    </td>
                </tr>
                <tr>
                    <th>Price</th>
                    <td>
                        <?php echo $product->getPrice(); ?>
                    </td>
                </tr>
                <form method="POST" action="<?php echo $this->getUrl('sales/quote/add') ?>">

                    <td>
                        <div class="form">
                            <div class="row">
                                <input type="hidden" name="sales_quote[product_id]" value="<?php echo $product->getProductId(); ?>">
                            </div>
                            <div class="row">
                                <label for="quantity">Quantity : </label>
                                <input type="number" name="sales_quote[qty]" id="quentity" min="1" max="<?php echo $product->getInventory();?>">
                            </div>
                    </td>

                    <td>
                        <div class="row">
                            <input type="submit" value="AddToCart">
                        </div>
                    </td>

                </form>
            </table>

        </div>
    <?php } ?>
</div>